### ISSUE TITLE
bits available for quantization

### ISSUE THREAD

**Issue by bmegli** [catid/Zdepth#11]
Hi @catid 

Currently implemented quantization is 11 bit (2040 distinct values)

https://github.com/catid/Zdepth/blob/ac7c6d8e944d07be2404e5a1eaa04562595f3756/include/zdepth.hpp#L180-L189

1. Do I understand correctly that it is because:
- zig-zag encoded predictor for +- value will be 12 bit in that case
- so the values can be at most 11 bit

2. Could quantization (theoretically) be extended to 12 bits by:
- adding deviation from 12 bit max predictor (~4096)
- adding deviation from 0 predictor
- handling edge cases when predictor value would exceed 11 bit in absolute value
  - we would always have guaranteed at least one correct 11 bit absolute value predictor

Kind regards

**Comment by bmegli** [comment]
> 2. Could quantization (theoretically) be extended to 12 bits by:
> - adding deviation from 12 bit max predictor (~4096)
> - adding deviation from 0 predictor
> - handling edge cases when predictor value would exceed 11 bit in absolute value
>   - we would always have guaranteed at least one correct 11 bit absolute value predictor

This would not work as predictors are chosen for whole blocks. There is no guarantee that single predictor exists for all values in the block.

What might work instead is:
- fallback predictor "deviation from `2^11=2048`"
  - which is always guaranteed to be correctly defined for each block
- handling edge cases as earlier

Whether it would hurt compression is another discussion.
Fallback predictor should happen rarely (as it mostly means all other predictors failed)

**Comment by catid** [comment]
Sounds like you have the right idea, which is the important thing.  There are lots of ways to do this once you get the basics down.  I haven't looked at this code for a long time so don't have a lot of good feedback.

**Comment by bmegli** [comment]
Thanks!
