### ISSUE TITLE
Speed benchmark

### ISSUE THREAD

**Issue by Changliu52** [catid/Zdepth#6]
Hi @catid ,

Thanks for sharing the awesome project.

> It runs in 1-2 milliseconds and produces compressed lossless depth video at 4-5 Mbps.

This is impressive real-time performance. 

I wonder what is the testing CPU? is it runing on single core without any GPU acceleration? What is the CPU utilisation at the speed?

Looking forward to your reply.

Best Regards,
Chang

**Comment by catid** [comment]
It's running on an i9 desktop.  Just a single thread I think, using default settings on Zstd.  Should fit on any platform you want to run it on.

**Comment by Changliu52** [comment]
Great. Thanks
